USE [master]
GO

/****** Object:  Database [WooHoo]    Script Date: 12.06.2024 14:32:13 ******/
DROP DATABASE [WooHoo]
GO

/****** Object:  Database [WooHoo]    Script Date: 12.06.2024 14:32:13 ******/
CREATE DATABASE [WooHoo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WooHoo', FILENAME = N'C:\Sql Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\WooHoo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WooHoo_log', FILENAME = N'C:\Sql Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\WooHoo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WooHoo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WooHoo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WooHoo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WooHoo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WooHoo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WooHoo] SET ARITHABORT OFF 
GO

ALTER DATABASE [WooHoo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WooHoo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WooHoo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WooHoo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WooHoo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WooHoo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WooHoo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WooHoo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WooHoo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WooHoo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WooHoo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WooHoo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WooHoo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WooHoo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WooHoo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WooHoo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WooHoo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WooHoo] SET RECOVERY FULL 
GO

ALTER DATABASE [WooHoo] SET  MULTI_USER 
GO

ALTER DATABASE [WooHoo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WooHoo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WooHoo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WooHoo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WooHoo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WooHoo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WooHoo] SET QUERY_STORE = ON
GO

ALTER DATABASE [WooHoo] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [WooHoo] SET  READ_WRITE 
GO

